### ISSUE TITLE
NoSuchMethodError while working with API

### ISSUE THREAD

**Issue by PinoOG** [erikzimmermann/WarpSystem-API#1]
After following the tutorial, working with IntelliJ and Maven there is this error triggered on every type of teleport
Plugin version: 5.1.3

` [14:07:52 ERROR]: Could not pass event AsyncPlayerTeleportEvent to ImperiCore v1.0
java.lang.NoSuchMethodError: 'de.codingair.codingapi.tools.Location de.codingair.warpsystem.api.destinations.utils.IDestination.buildLocation()'
        at org.natorog.imperialimpericore.eventi.TeleportCapture.onTeleport(TeleportCapture.java:34) ~[ImperiCore-1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor838.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfishplus-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfishplus-api-1.19.2-R0.1-SNAPSHOT.jar:git-PufferfishPlus-32]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfishplus-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfishplus-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at de.codingair.warpsystem.spigot.base.utils.teleport.process.Teleport.lambda$start$1(Teleport.java:32) ~[WarpSystem_v5.1.3-free.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run() ~[pufferfishplus-1.19.2.jar:git-PufferfishPlus-32]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run() ~[pufferfishplus-1.19.2.jar:git-PufferfishPlus-32]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run() ~[pufferfishplus-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?] `
        
        CODE
        
        `    @EventHandler
    public void onTeleport(AsyncPlayerTeleportEvent e) {
        if (e.isCancelled()) return;

        if (e.getPlayer().hasPermission("impericore.bypass")) return;

        IDestination destination = e.getOptions().getDestination();
        Location finalLocation = destination.buildLocation();

        if (finalLocation != null){
            String name = finalLocation.getWorldName();
            Options options = e.getOptions();
            e.getPlayer().sendMessage("NEGRO");
        if (worldList.contains(name)) {
            if (options.getOrigin().equals(Origin.TeleportRequest)) {
                e.setCancelled(true);
            }
        }
    }
    }`
    
    POM
    
    `        <dependency>
            <groupId>com.github.CodingAir</groupId>
            <artifactId>WarpSystem-API</artifactId>
            <version>5.0.6</version>
            <scope>provided</scope>
        </dependency>

        
        <dependency>
            <groupId>com.github.CodingAir</groupId>
            <artifactId>CodingAPI</artifactId>
            <version>1.35</version>
            <scope>provided</scope>
        </dependency>`

**Comment by erikzimmermann** [comment]
You probably have to update the WarpSystem. Please comment if this issue persists...
